# Workflow for deploying beta release

name: Deploy beta version
on:
  schedule:
    - cron: '0 0 * * 2' # Every Tuesday at 0000 UTC

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: 'Deploy beta version'
    runs-on: ubuntu-latest

    environment: Deploy

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java for deploy
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          java-package: jdk
          architecture: x64
          distribution: adopt

          server-id: ossrh
          server-username: SONATYPE_USER
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.SPOONBOT_GPG_KEY }}
          gpg-passphrase: SPOONBOT_PASSPHRASE

      - name: Start deployment
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SPOONBOT_PASSPHRASE: ${{ secrets.SPOONBOT_PASSPHRASE }}
        run: ./deploy-spoon-maven-central.sh
