# Workflow for deploying beta release

name: Deploy beta version
on:
  push:
      branches: [master]

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: 'Deploy beta version'
    runs-on: ubuntu-latest

    environment: Deploy

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start deployment
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SPOONBOT_PASSPHRASE: ${{ secrets.SPOONBOT_PASSPHRASE }}
        run: ./deploy-spoon-maven-central.sh
